name: CI
on: push

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: make install

    - name: Build project
      run: make build

    - name: Run tests
      run: make test

    - name: Run linter
      run: make lint